# Generated by Django 5.1.4 on 2024-12-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_privatechatroom_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='guest_user',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='guest_sender',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
