# Generated by Django 5.1.4 on 2024-12-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_privatechatroom_guest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='guest_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='guest_sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
