# Generated by Django 5.1.4 on 2024-12-19 00:18

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(default=base.models.generate_tracking_id, max_length=20, unique=True),
        ),
    ]
