# Generated by Django 5.1.4 on 2024-12-19 01:29

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_shipment_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
