# Generated by Django 5.1.4 on 2024-12-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_shipment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
